# Site settings
title: Team S66 - Semantic Networks - UNWE.BG
author: Lubomir Georgiev
email: lubomirgeorgievgeorgiev@gmail.com
description: Semantic Networks Assignment at UNWE.BG - Team S66
version: v1.0.2
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:
project_repo: https://github.com/LubomirGeorgiev/UNSS-S66-Semantic-Networks
project_url: http://lubomirgeorgiev.github.io/UNSS-S66-Semantic-Networks


# Build settings
destination: _dist
source: source
markdown: kramdown
highlighter: rouge
sass:
    style: compressed
